### ISSUE TITLE
Help wanted from the original gamedev

### ISSUE THREAD

**Issue by blubbll** [blubbll/pangenes#1]
@BenTaylorPublic, do you mind sharing more info on the protocol?

**Comment by BenTaylorPublic** [comment]
You've got the wrong person

**Comment by blubbll** [comment]
> You've got the wrong person

dang i thought there cannot be _that_ many aussie Ben Taylor Devs lol https://twitter.com/bensgames

**Comment by blubbll** [comment]
@sunnyjum then

**Comment by blubbll** [comment]
apparently sunnyjum doesn't want to share anything.

**Comment by Tachytaenius** [comment]
That's what they've told you?

**Comment by blubbll** [comment]
@wolfboyft that's why i wrote "apparently". He doesnt respond to any direct messages at least on reddit, while being most active on thst platform, doesnt fix the website bugs and didnt ever publicly mention pangenesis again even though hes active across all social media on the same accounts

**Comment by wolfboyft** [comment]
Wonder if there's some sort of emotional baggage tied to the game he's trying to escape from... anyway, ta.
